### ISSUE TITLE
tasks not getting schedule

### ISSUE THREAD

**Issue by gsowmya2910** [tiburon-security/jupyterlab_scheduler#11]
![image](https://user-images.githubusercontent.com/28769052/110199647-fcc7c000-7e1e-11eb-9ab9-c825ef79d0ee.png)
![image](https://user-images.githubusercontent.com/28769052/110199680-30a2e580-7e1f-11eb-835a-8126f414818e.png)

Could find the schedule button as shown in your documents.
![image](https://user-images.githubusercontent.com/28769052/110199734-765fae00-7e1f-11eb-95da-db4217d80d8a.png)

Please help me out

**Comment by winwish** [comment]
I have the same problem, running jupyter lab on docker on Synology, is it possible to get it working?
![Uploading schedulererror.png…]()

**Comment by admay** [comment]
Seems to be an installation issue: https://github.com/tiburon-security/jupyterlab_scheduler/issues/10

**Comment by jovanni-hernandez** [comment]
Newest version released which fixes this issue and other installation issues.
