### ISSUE TITLE
problems with installation

### ISSUE THREAD

**Issue by losrobertos** [tiburon-security/jupyterlab_scheduler#12]
Current plugin is older than jupiterlab version. what went wrong? Please advice what to do next

An error occured.
ValueError:
"jupyterlab_scheduler@0.1.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab             Extension      Package
>=3.0.4 <3.1.0         >=2.2.1 <3.0.0 @jupyterlab/mainmenu
>=5.0.2 <5.1.0         >=4.0.2 <5.0.0 @jupyterlab/coreutils
>=3.0.5 <3.1.0         >=2.0.2 <3.0.0 @jupyterlab/rendermime
>=6.0.4 <6.1.0         >=5.0.2 <6.0.0 @jupyterlab/services
See the log file for details:  /tmp/jupyterlab-debug-bv3e61o3.log

**Comment by losrobertos** [comment]
@admay Could you please give an advise?

**Comment by admay** [comment]
@losrobertos fair warning, I'm not a maintainer or contributor for this library, so I don't know how much help I'm going to be.

Can you send me the following:
1. command run to get this output
2. full output
3. log file output

Also, can you answer the following for me:
1. What are you using to install?
2. Are you running within a virtual environment? If so, through what? Conda, virtualenv, etc...
3. What other packages ( and versions ) do you have installed in the environment you're running this in? `pip freeze` output. For conda it's `conda env export` I believe.

**Comment by losrobertos** [comment]
1.2.3.
# npm install
> core-js@3.15.1 postinstall /opt/node/jupyterlab_scheduler-master/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock
Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @lumino/coreutils@1.8.0 requires a peer of crypto@1.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.2.2 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN css-loader@3.6.0 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@4.3.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
added 1 package in 4.78s
49 packages are looking for funding
 run `npm fund` for details
# npm run build:lib
> jupyterlab_scheduler@0.1.3 build:lib /opt/node/jupyterlab_scheduler-master
> babel src --out-dir lib
Successfully compiled 5 files with Babel (1156ms).
# jupyter labextension install
An error occured.
ValueError:
"jupyterlab_scheduler@0.1.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab Extension Package
>=3.0.9 <3.1.0 >=2.2.1 <3.0.0 @jupyterlab/mainmenu
>=5.0.6 <5.1.0 >=4.0.2 <5.0.0 @jupyterlab/coreutils
>=3.0.10 <3.1.0 >=2.0.2 <3.0.0 @jupyterlab/rendermime
>=6.0.9 <6.1.0 >=5.0.2 <6.0.0 @jupyterlab/services
See the log file for details: /tmp/jupyterlab-debug-y_n4p077.log

----

1. What are you using to install?

Npm and jupyter labextension install

2. Are you running within a virtual environment? If so, through what? Conda, virtualenv, etc...

Without venv

3. What other packages ( and versions ) do you have installed in the environment you're running this in? pip freeze output. For 
conda it's conda env export I believe.

# pip freeze
alembic==1.6.5
anyio==3.2.1
argon2-cffi==20.1.0
async-generator==1.10
attrs==21.2.0
Babel==2.9.1
backcall==0.2.0
bleach==3.3.0
certifi==2021.5.30
certipy==0.1.3
cffi==1.14.5
chardet==4.0.0
contextvars==2.4
cryptography==3.4.7
dataclasses==0.8
decorator==5.0.9
defusedxml==0.7.1
entrypoints==0.3
greenlet==1.1.0
idna==2.10
immutables==0.15
importlib-metadata==4.5.0
ipykernel==5.5.5
ipython==7.16.1
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==3.0.1
json5==0.9.6
jsonschema==3.2.0
jupyter-client==6.2.0
jupyter-core==4.7.1
jupyter-server==1.9.0
jupyter-telemetry==0.1.0
jupyterhub==1.4.1
jupyterlab==3.0.16
jupyterlab-pygments==0.1.2
jupyterlab-server==2.6.0
jupyterlab-widgets==1.0.0
Mako==1.1.4
MarkupSafe==2.0.1
mistune==0.8.4
nbclassic==0.3.1
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.0
oauthlib==3.1.1
packaging==20.9
pamela==1.0.0
pandocfilters==1.4.3
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.11.0
prompt-toolkit==3.0.19
ptyprocess==0.7.0
pycparser==2.20
Pygments==2.9.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
python-editor==1.0.4
python-json-logger==2.0.1
pytz==2021.1
pyzmq==22.1.0
requests==2.25.1
requests-unixsocket==0.2.0
ruamel.yaml==0.17.10
ruamel.yaml.clib==0.2.4
Send2Trash==1.7.1
six==1.16.0
sniffio==1.2.0
SQLAlchemy==1.4.19
testpath==0.5.0
tornado==6.1
traitlets==4.3.3
typing-extensions==3.10.0.0
urllib3==1.26.5
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.1.0
widgetsnbextension==3.5.1
zipp==3.4.1

**Comment by jovanni-hernandez** [comment]
@admay thanks for helping out while I've been on a hiatus

@losrobertos I'm working on getting the tool working on the latest version of jupyterlab now, hopefully this isn't too painful of an upgrade

**Comment by jovanni-hernandez** [comment]
New version released that compatible with the latest Jupyter Labs
