### ISSUE TITLE
How to interpret Status: Failed 

### ISSUE THREAD

**Issue by ThomasMGeo** [tiburon-security/jupyterlab_scheduler#30]
Hello,

I am getting output files, and things seem to run but the status 'Failed' happens. 

![Screen Shot 2023-04-17 at 10 29 41 AM](https://user-images.githubusercontent.com/38228140/232550793-da43fba6-61b7-464f-8a03-202270cee8cb.png)

**Comment by jovanni-hernandez** [comment]
Hi Thomas. This plugin is no longer supported as the Jupyter Project released an official plugin with the same functionality:

https://github.com/jupyter-server/jupyter-scheduler

I recommend checking that project out as it's under active development. Their UI is also much nicer!
